### ISSUE TITLE
More of a question than anything

### ISSUE THREAD

**Issue by joe-gaudet-hs** [montemishkin/slush-ease#1]
Enjoying slush-ease, any thoughts on testing tasks?

**Comment by montemishkin** [comment]
Thanks for your interest, I'm glad you have enjoyed the package!

I am currently in the process of reconceptualizing my approach towards generator related tools.  As a result, I have halted with my work on slush-ease, and **currently do not have any plans to implement tools for testing tasks in slush-ease**.

However, I would be happy to look over any pull requests you might (or might not) make.  Feel free (or not) to tackle it yourself.  
Also, if you would like, I'll let you know when/if I find time to bring my reconceptualization into fruition (tools for testing tasks would certainly be on the schedule for such a project).
